2023-05-01 21:35:33,337 INFO    StreamThr :76731 [internal.py:wandb_internal():86] W&B internal server running at pid: 76731, started at: 2023-05-01 21:35:33.337165
2023-05-01 21:35:33,338 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: status
2023-05-01 21:35:33,339 INFO    WriterThread:76731 [datastore.py:open_for_write():85] open: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/run-gxcglp1i.wandb
2023-05-01 21:35:33,340 DEBUG   SenderThread:76731 [sender.py:send():375] send: header
2023-05-01 21:35:33,357 DEBUG   SenderThread:76731 [sender.py:send():375] send: run
2023-05-01 21:35:33,620 INFO    SenderThread:76731 [dir_watcher.py:__init__():219] watching files in: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files
2023-05-01 21:35:33,620 INFO    SenderThread:76731 [sender.py:_start_run_threads():1124] run started: gxcglp1i with start time 1682991333.336109
2023-05-01 21:35:33,621 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: summary_record
2023-05-01 21:35:33,621 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:33,627 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: check_version
2023-05-01 21:35:33,628 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: check_version
2023-05-01 21:35:33,763 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: run_start
2023-05-01 21:35:33,786 DEBUG   HandlerThread:76731 [system_info.py:__init__():31] System info init
2023-05-01 21:35:33,786 DEBUG   HandlerThread:76731 [system_info.py:__init__():46] System info init done
2023-05-01 21:35:33,786 INFO    HandlerThread:76731 [system_monitor.py:start():181] Starting system monitor
2023-05-01 21:35:33,787 INFO    SystemMonitor:76731 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-05-01 21:35:33,787 INFO    HandlerThread:76731 [system_monitor.py:probe():201] Collecting system info
2023-05-01 21:35:33,788 INFO    SystemMonitor:76731 [interfaces.py:start():190] Started cpu monitoring
2023-05-01 21:35:33,788 DEBUG   HandlerThread:76731 [system_info.py:probe():195] Probing system
2023-05-01 21:35:33,788 INFO    SystemMonitor:76731 [interfaces.py:start():190] Started disk monitoring
2023-05-01 21:35:33,789 INFO    SystemMonitor:76731 [interfaces.py:start():190] Started memory monitoring
2023-05-01 21:35:33,789 INFO    SystemMonitor:76731 [interfaces.py:start():190] Started network monitoring
2023-05-01 21:35:33,797 DEBUG   HandlerThread:76731 [system_info.py:_probe_git():180] Probing git
2023-05-01 21:35:33,816 DEBUG   HandlerThread:76731 [system_info.py:_probe_git():188] Probing git done
2023-05-01 21:35:33,816 DEBUG   HandlerThread:76731 [system_info.py:probe():240] Probing system done
2023-05-01 21:35:33,816 DEBUG   HandlerThread:76731 [system_monitor.py:probe():210] {'os': 'macOS-10.16-x86_64-i386-64bit', 'python': '3.9.16', 'heartbeatAt': '2023-05-02T01:35:33.788596', 'startedAt': '2023-05-02T01:35:33.328495', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/mt361/Desktop/RL-Bandits/train.py', 'codePath': 'train.py', 'git': {'remote': 'git@github.com:MuhangTian/Deep-RL.git', 'commit': '4de0375f35e2c3322d00308c71763539bc5ee74c'}, 'email': 'mt361@duke.edu', 'root': '/Users/mt361/Desktop/RL-Bandits', 'host': 'MacBook-Pro-73.local', 'username': 'mt361', 'executable': '/usr/local/anaconda3/envs/RL/bin/python', 'cpu_count': 12, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2400, 'min': 2400, 'max': 2400}, 'cpu_freq_per_core': [{'current': 2400, 'min': 2400, 'max': 2400}], 'disk': {'total': 926.3517189025879, 'used': 11.967166900634766}, 'memory': {'total': 16.0}}
2023-05-01 21:35:33,816 INFO    HandlerThread:76731 [system_monitor.py:probe():211] Finished collecting system info
2023-05-01 21:35:33,816 INFO    HandlerThread:76731 [system_monitor.py:probe():214] Publishing system info
2023-05-01 21:35:33,816 DEBUG   HandlerThread:76731 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-05-01 21:35:33,816 DEBUG   HandlerThread:76731 [system_info.py:_save_pip():67] Saving pip packages done
2023-05-01 21:35:33,816 DEBUG   HandlerThread:76731 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-05-01 21:35:34,623 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/conda-environment.yaml
2023-05-01 21:35:34,623 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/requirements.txt
2023-05-01 21:35:34,623 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-summary.json
2023-05-01 21:35:36,374 DEBUG   HandlerThread:76731 [system_info.py:_save_conda():86] Saving conda packages done
2023-05-01 21:35:36,375 INFO    HandlerThread:76731 [system_monitor.py:probe():216] Finished publishing system info
2023-05-01 21:35:36,377 DEBUG   SenderThread:76731 [sender.py:send():375] send: files
2023-05-01 21:35:36,377 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-05-01 21:35:36,430 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: stop_status
2023-05-01 21:35:36,431 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: stop_status
2023-05-01 21:35:36,528 DEBUG   SenderThread:76731 [sender.py:send():375] send: telemetry
2023-05-01 21:35:36,632 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/conda-environment.yaml
2023-05-01 21:35:36,632 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-metadata.json
2023-05-01 21:35:36,877 INFO    wandb-upload_0:76731 [upload_job.py:push():137] Uploaded file /var/folders/t0/wpl_qfjd5s3cczhlskc092xm0000gp/T/tmpl6m4lg21wandb/iju56dig-wandb-metadata.json
2023-05-01 21:35:38,539 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: status_report
2023-05-01 21:35:40,858 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: partial_history
2023-05-01 21:35:40,859 DEBUG   SenderThread:76731 [sender.py:send():375] send: history
2023-05-01 21:35:40,859 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: summary_record
2023-05-01 21:35:40,860 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:41,651 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-summary.json
2023-05-01 21:35:41,651 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_created():278] file/dir created: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/output.log
2023-05-01 21:35:43,662 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/output.log
2023-05-01 21:35:43,874 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: status_report
2023-05-01 21:35:44,251 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: partial_history
2023-05-01 21:35:44,252 DEBUG   SenderThread:76731 [sender.py:send():375] send: history
2023-05-01 21:35:44,252 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: summary_record
2023-05-01 21:35:44,253 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:44,667 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-summary.json
2023-05-01 21:35:45,673 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/output.log
2023-05-01 21:35:48,209 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: partial_history
2023-05-01 21:35:48,210 DEBUG   SenderThread:76731 [sender.py:send():375] send: history
2023-05-01 21:35:48,211 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: summary_record
2023-05-01 21:35:48,211 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:48,688 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-summary.json
2023-05-01 21:35:49,216 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: status_report
2023-05-01 21:35:49,691 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/output.log
2023-05-01 21:35:51,435 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: stop_status
2023-05-01 21:35:51,436 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: stop_status
2023-05-01 21:35:51,740 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: partial_history
2023-05-01 21:35:51,741 DEBUG   SenderThread:76731 [sender.py:send():375] send: history
2023-05-01 21:35:51,741 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: summary_record
2023-05-01 21:35:51,742 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:52,706 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-summary.json
2023-05-01 21:35:52,776 DEBUG   SenderThread:76731 [sender.py:send():375] send: exit
2023-05-01 21:35:52,776 INFO    SenderThread:76731 [sender.py:send_exit():598] handling exit code: 255
2023-05-01 21:35:52,776 INFO    SenderThread:76731 [sender.py:send_exit():600] handling runtime: 19
2023-05-01 21:35:52,776 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:52,777 INFO    SenderThread:76731 [sender.py:send_exit():606] send defer
2023-05-01 21:35:52,777 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,777 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 0
2023-05-01 21:35:52,777 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,777 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 0
2023-05-01 21:35:52,777 INFO    SenderThread:76731 [sender.py:transition_state():626] send defer: 1
2023-05-01 21:35:52,777 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,777 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 1
2023-05-01 21:35:52,777 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,777 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 1
2023-05-01 21:35:52,777 INFO    SenderThread:76731 [sender.py:transition_state():626] send defer: 2
2023-05-01 21:35:52,777 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,777 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 2
2023-05-01 21:35:52,777 INFO    HandlerThread:76731 [system_monitor.py:finish():190] Stopping system monitor
2023-05-01 21:35:52,777 INFO    HandlerThread:76731 [interfaces.py:finish():202] Joined cpu monitor
2023-05-01 21:35:52,777 DEBUG   SystemMonitor:76731 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-05-01 21:35:52,777 INFO    HandlerThread:76731 [interfaces.py:finish():202] Joined disk monitor
2023-05-01 21:35:52,778 DEBUG   SystemMonitor:76731 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-05-01 21:35:52,778 INFO    HandlerThread:76731 [interfaces.py:finish():202] Joined memory monitor
2023-05-01 21:35:52,778 DEBUG   SystemMonitor:76731 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-05-01 21:35:52,778 INFO    HandlerThread:76731 [interfaces.py:finish():202] Joined network monitor
2023-05-01 21:35:52,778 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,778 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 2
2023-05-01 21:35:52,778 INFO    SenderThread:76731 [sender.py:transition_state():626] send defer: 3
2023-05-01 21:35:52,778 DEBUG   SenderThread:76731 [sender.py:send():375] send: stats
2023-05-01 21:35:52,778 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,778 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 3
2023-05-01 21:35:52,779 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 3
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:transition_state():626] send defer: 4
2023-05-01 21:35:52,779 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,779 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 4
2023-05-01 21:35:52,779 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 4
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:transition_state():626] send defer: 5
2023-05-01 21:35:52,779 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,779 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 5
2023-05-01 21:35:52,779 DEBUG   SenderThread:76731 [sender.py:send():375] send: summary
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-01 21:35:52,779 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 5
2023-05-01 21:35:52,779 INFO    SenderThread:76731 [sender.py:transition_state():626] send defer: 6
2023-05-01 21:35:52,780 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: defer
2023-05-01 21:35:52,780 INFO    HandlerThread:76731 [handler.py:handle_request_defer():170] handle defer: 6
2023-05-01 21:35:52,780 DEBUG   SenderThread:76731 [sender.py:send_request():402] send_request: defer
2023-05-01 21:35:52,780 INFO    SenderThread:76731 [sender.py:send_request_defer():622] handle sender defer: 6
2023-05-01 21:35:52,782 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: status_report
2023-05-01 21:35:52,864 ERROR   SenderThread:76731 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-01 21:35:52,864 ERROR   SenderThread:76731 [internal_api.py:execute():289] {"errors":[{"message":"run dukeds-mimic2023/RL-implementation/gxcglp1i was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-01 21:35:53,712 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/output.log
2023-05-01 21:35:53,713 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/wandb-summary.json
2023-05-01 21:35:53,779 DEBUG   HandlerThread:76731 [handler.py:handle_request():144] handle_request: poll_exit
2023-05-01 21:35:54,168 ERROR   SenderThread:76731 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-01 21:35:54,169 ERROR   SenderThread:76731 [internal_api.py:execute():289] {"errors":[{"message":"run dukeds-mimic2023/RL-implementation/gxcglp1i was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-01 21:35:55,717 INFO    Thread-12 :76731 [dir_watcher.py:_on_file_modified():295] file/dir modified: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/files/output.log
2023-05-01 21:35:56,667 ERROR   SenderThread:76731 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-01 21:35:56,667 ERROR   SenderThread:76731 [internal_api.py:execute():289] {"errors":[{"message":"run dukeds-mimic2023/RL-implementation/gxcglp1i was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-01 21:35:56,667 INFO    SenderThread:76731 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-05-01 21:35:58,440 WARNING StreamThr :76731 [internal.py:is_dead():414] Internal process exiting, parent pid 76722 disappeared
2023-05-01 21:35:58,441 ERROR   StreamThr :76731 [internal.py:wandb_internal():152] Internal process shutdown.
2023-05-01 21:35:58,797 INFO    WriterThread:76731 [datastore.py:close():298] close: /Users/mt361/Desktop/RL-Bandits/wandb/run-20230501_213533-gxcglp1i/run-gxcglp1i.wandb
2023-05-01 21:35:58,797 INFO    HandlerThread:76731 [handler.py:finish():845] shutting down handler
2023-05-01 21:36:00,858 ERROR   SenderThread:76731 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-01 21:36:00,858 ERROR   SenderThread:76731 [internal_api.py:execute():289] {"errors":[{"message":"run dukeds-mimic2023/RL-implementation/gxcglp1i was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-01 21:36:09,698 ERROR   SenderThread:76731 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-01 21:36:09,699 ERROR   SenderThread:76731 [internal_api.py:execute():289] {"errors":[{"message":"run dukeds-mimic2023/RL-implementation/gxcglp1i was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-01 21:36:29,574 ERROR   SenderThread:76731 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-01 21:36:29,575 ERROR   SenderThread:76731 [internal_api.py:execute():289] {"errors":[{"message":"run dukeds-mimic2023/RL-implementation/gxcglp1i was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-01 21:36:29,575 ERROR   StreamThr :76731 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1690, in upsert_run
    response = self.gql(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 257, in gql
    ret = self._retry_gql(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 291, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 328, in _process
    self._sm.send(record)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 382, in send
    send_handler(record)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 404, in send_request
    send_handler(record)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 648, in send_request_defer
    self.debounce(final=True)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 551, in debounce
    self._maybe_update_config(always=final)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 528, in _maybe_update_config
    self._debounce_config()
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 557, in _debounce_config
    self._api.upsert_run(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1690, in upsert_run
    response = self.gql(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 257, in gql
    ret = self._retry_gql(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 291, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/usr/local/anaconda3/envs/RL/lib/python3.9/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
wandb.errors.CommError: [Errno 5] Input/output error
2023-05-02 12:40:42,162 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-02 12:43:45,029 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 00:20:57,206 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 01:12:06,015 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 02:57:09,639 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:55:58,614 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:56:00,818 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b9040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:56:05,496 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b91c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:56:14,284 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b9fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:56:31,768 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b92b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:57:05,561 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b9fa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 10:58:18,672 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b97c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 11:00:49,632 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b9400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 11:05:17,157 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe307b9ee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-03 18:08:33,940 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-04 01:59:10,359 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-04 02:41:36,483 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-04 09:00:00,865 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
2023-05-04 13:39:05,326 WARNING FileStreamThread:76731 [file_stream.py:request_with_retry():670] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=None). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbde005c370>>, args: ('https://api.wandb.ai/files/dukeds-mimic2023/RL-implementation/gxcglp1i/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 7, 'uploaded': ['wandb-metadata.json']}}
